### PR TITLE
Rename default branch

### PR DESCRIPTION
**Pull request by larryfenn**
Ran into this today using an updated version of `git` -- the default branch is now `main`, in both `git` and in GitLab going forward: https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/

### CODE REVIEW

**Comment by larryfenn** [comment]
Note there are some tests that still use `master`:

- `tests/fixtures/group_id_lookup.json`
- `tests/fixtures/project_search-already_exists.json`
- `tests/fixtures/project_get.json`
- `tests/commands/test_integrate.py`

Not sure how to handle them.

**Comment by myersjustinc** [comment]
Definitely in favor of this change, and even would be in favor of updating our existing repos for these plugins to reflect the updated convention.

If users do _not_ have their local Git installations set up to use `main` as the default branch for new repositories, though, it's very likely this change (as written) will fail.

As of Git 2.28.0, `git init` supports an `--initial-branch` option, so ideally we could be explicit in this same file about running `git init --initial-branch main` rather than just `git init`—but 2.28 only came out the summer before last, and a lot of people haven't set up new machines since then. (For that matter, [the current Ubuntu LTS only offers 2.25](https://packages.ubuntu.com/focal/git).)

The more backward-compatible approach might be to leave the `git init` call as is and to run `git branch --move main` immediately after the initial commit. (The `--move` option for `git branch`, which renames a branch, [has been around since late 2006](https://github.com/git/git/commit/c976d415e5352886f0650f8e2edba81866c38587), which seems safe enough.)

I've tried this locally under Git 2.32.0 and in a container with Git 2.19.1 (the oldest available tag for the `bitnami/git` image), and it doesn't seem to cause an error if you try using that command to change your (implied) current branch's name to the same name it already has. (That said, 2.32 let me run it before a commit even existed, but 2.19 required there to be an existing commit first.)

For the tests: These are specific to our GitLab API interactions, and my gut says the tests won't care if the projects' default branches are changed in those JSON bodies. (At first glance, I don't see the tests looking _that_ closely at their contents.) We _will_ want to update `tests/commands/test_integrate.py` to reflect the list of Git commands we actually run, [which currently lives at 45-51](https://github.com/associatedpress/datakit-gitlab/blob/ecaad2d845bb9c93b5fb1efb6e26069af94c62ad/tests/commands/test_integrate.py#L45-L51).

**Comment by zstumgoren** [comment]
+1 to the idea of a more robust solution to nudging `master` -> `main` for folks on older versions of git. I'd vote for the backwards-compatible `git branch --move main` option mentioned by @myersjustinc, combined with a prominent heads up in the shell logging that this action was performed by default.

But I'm open to your other options as well. Let me know what you all settle on and I'll plan to mirror the approach over on [datakit-github](https://github.com/associatedpress/datakit-github).

**Comment by myersjustinc** [comment]
Updated, and merging. Only change in the command's code itself other than the one @larryfenn first added here is to call `git branch --move main` as discussed above. All other changes here are in order to get the test suite back in working order, as noted in #4.

**Comment by myersjustinc** [comment]
Related, I'll be changing the name of _this_ repo's default branch while I'm already here and before cutting a new release.

**Pull request merged**
